import type { Player, Challenge, LeaderboardEntry } from '../types';

export const mockPlayer: Player = {
  id: 'player-1',
  githubUsername: 'octocat',
  displayName: 'The Octocat',
  avatar: 'https://github.com/octocat.png',
  level: 7,
  xp: 7420,
  totalPoints: 15840,
  currentStreak: 5,
  longestStreak: 12,
  joinedAt: new Date('2024-01-01'),
  achievements: [
    {
      id: 'first-pattern',
      name: 'First Pattern',
      description: 'Created your first pattern',
      icon: '🎯',
      unlockedAt: new Date('2024-01-02'),
      rarity: 'common',
      points: 100,
    },
    {
      id: 'week-warrior',
      name: 'Week Warrior',
      description: 'Completed 7 challenges in a week',
      icon: '⚔️',
      unlockedAt: new Date('2024-01-08'),
      rarity: 'rare',
      points: 500,
    },
    {
      id: 'speed-demon',
      name: 'Speed Demon',
      description: 'Completed a hard challenge in under 10 minutes',
      icon: '⚡',
      unlockedAt: new Date('2024-01-15'),
      rarity: 'epic',
      points: 1000,
    },
  ],
  stats: {
    patternsCreated: 42,
    challengesCompleted: 38,
    battlesWon: 12,
    reviewsGiven: 67,
    helpfulVotes: 145,
    averageScore: 850,
    favoriteCategory: 'cards',
  },
};

export const mockChallenges: Challenge[] = [
  {
    id: 'daily-1',
    title: 'Modern Login Form',
    description: 'Create a responsive login form with social auth options and remember me functionality',
    difficulty: 'easy',
    category: 'auth',
    requirements: [
      {
        id: 'req-1',
        description: 'Include email and password fields',
        type: 'component',
      },
      {
        id: 'req-2',
        description: 'Add social login buttons (Google, GitHub)',
        type: 'component',
      },
      {
        id: 'req-3',
        description: 'Implement form validation',
        type: 'feature',
      },
      {
        id: 'req-4',
        description: 'Make it fully responsive',
        type: 'feature',
      },
    ],
    timeLimit: 30,
    points: 500,
    bonusPoints: [
      {
        description: 'Complete in under 15 minutes',
        points: 100,
        condition: 'time < 15',
      },
      {
        description: 'Add password strength indicator',
        points: 50,
        condition: 'hasPasswordStrength',
      },
    ],
    createdAt: new Date(),
    completions: 142,
    averageScore: 480,
  },
  {
    id: 'daily-2',
    title: 'Analytics Dashboard Card',
    description: 'Design a card component that displays key metrics with charts and trend indicators',
    difficulty: 'medium',
    category: 'dashboards',
    requirements: [
      {
        id: 'req-1',
        description: 'Display at least 3 different metrics',
        type: 'component',
      },
      {
        id: 'req-2',
        description: 'Include a mini chart (line or bar)',
        type: 'component',
      },
      {
        id: 'req-3',
        description: 'Show trend indicators (up/down)',
        type: 'feature',
      },
      {
        id: 'req-4',
        description: 'Support dark mode',
        type: 'feature',
      },
    ],
    timeLimit: 45,
    points: 800,
    bonusPoints: [
      {
        description: 'Add interactive hover states',
        points: 100,
        condition: 'hasHoverStates',
      },
      {
        description: 'Include loading skeleton',
        points: 75,
        condition: 'hasLoadingSkeleton',
      },
    ],
    createdAt: new Date(),
    completions: 89,
    averageScore: 720,
  },
  {
    id: 'weekly-1',
    title: 'Multi-Step Form Wizard',
    description: 'Build a multi-step form with progress indicator, validation, and step navigation',
    difficulty: 'hard',
    category: 'forms',
    requirements: [
      {
        id: 'req-1',
        description: 'At least 3 steps with different form fields',
        type: 'component',
      },
      {
        id: 'req-2',
        description: 'Visual progress indicator',
        type: 'component',
      },
      {
        id: 'req-3',
        description: 'Step validation before proceeding',
        type: 'feature',
      },
      {
        id: 'req-4',
        description: 'Back/Next navigation with keyboard support',
        type: 'feature',
      },
      {
        id: 'req-5',
        description: 'Data persistence between steps',
        type: 'feature',
      },
    ],
    timeLimit: 60,
    points: 1200,
    bonusPoints: [
      {
        description: 'Add step animations',
        points: 150,
        condition: 'hasAnimations',
      },
      {
        description: 'Include form summary on last step',
        points: 100,
        condition: 'hasSummary',
      },
    ],
    createdAt: new Date(),
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 1 week
    completions: 34,
    averageScore: 980,
  },
  {
    id: 'epic-1',
    title: 'OpenGov Unified Header',
    description: 'Create a unified navigation header that works across all 6 acquisitions with theming support',
    difficulty: 'epic',
    category: 'navigation',
    requirements: [
      {
        id: 'req-1',
        description: 'Responsive navigation with mobile menu',
        type: 'component',
      },
      {
        id: 'req-2',
        description: 'Product switcher for 6+ products',
        type: 'component',
      },
      {
        id: 'req-3',
        description: 'User profile dropdown with actions',
        type: 'component',
      },
      {
        id: 'req-4',
        description: 'Theme switcher (6 acquisition themes)',
        type: 'feature',
      },
      {
        id: 'req-5',
        description: 'Search functionality',
        type: 'feature',
      },
      {
        id: 'req-6',
        description: 'Notification center',
        type: 'feature',
      },
      {
        id: 'req-7',
        description: 'Full keyboard navigation',
        type: 'accessibility',
      },
    ],
    points: 2000,
    bonusPoints: [
      {
        description: 'Add micro-interactions',
        points: 200,
        condition: 'hasMicroInteractions',
      },
      {
        description: 'Include AI-powered search',
        points: 300,
        condition: 'hasAISearch',
      },
    ],
    createdAt: new Date(),
    completions: 12,
    averageScore: 1650,
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    playerId: 'player-2',
    playerName: 'Sarah Chen',
    avatar: 'https://i.pravatar.cc/150?u=sarah',
    points: 28450,
    level: 15,
    streak: 28,
    change: 0,
  },
  {
    rank: 2,
    playerId: 'player-3',
    playerName: 'Alex Rivera',
    avatar: 'https://i.pravatar.cc/150?u=alex',
    points: 26890,
    level: 14,
    streak: 21,
    change: 1,
  },
  {
    rank: 3,
    playerId: 'player-4',
    playerName: 'Marcus Johnson',
    avatar: 'https://i.pravatar.cc/150?u=marcus',
    points: 24320,
    level: 13,
    streak: 15,
    change: -1,
  },
  {
    rank: 4,
    playerId: 'player-5',
    playerName: 'Emily Watson',
    avatar: 'https://i.pravatar.cc/150?u=emily',
    points: 22100,
    level: 12,
    streak: 18,
    change: 2,
  },
  {
    rank: 5,
    playerId: 'player-6',
    playerName: 'David Kim',
    avatar: 'https://i.pravatar.cc/150?u=david',
    points: 19870,
    level: 11,
    streak: 9,
    change: 0,
  },
  {
    rank: 6,
    playerId: 'player-7',
    playerName: 'Lisa Thompson',
    avatar: 'https://i.pravatar.cc/150?u=lisa',
    points: 18540,
    level: 10,
    streak: 12,
    change: -2,
  },
  {
    rank: 7,
    playerId: 'player-1',
    playerName: 'The Octocat',
    avatar: 'https://github.com/octocat.png',
    points: 15840,
    level: 7,
    streak: 5,
    change: 3,
  },
  {
    rank: 8,
    playerId: 'player-8',
    playerName: 'James Wilson',
    avatar: 'https://i.pravatar.cc/150?u=james',
    points: 14230,
    level: 8,
    streak: 7,
    change: -1,
  },
  {
    rank: 9,
    playerId: 'player-9',
    playerName: 'Nina Patel',
    avatar: 'https://i.pravatar.cc/150?u=nina',
    points: 12890,
    level: 7,
    streak: 3,
    change: 0,
  },
  {
    rank: 10,
    playerId: 'player-10',
    playerName: 'Robert Lee',
    avatar: 'https://i.pravatar.cc/150?u=robert',
    points: 11450,
    level: 6,
    streak: 10,
    change: -2,
  },
];